---
project_name: tfaction
archives:
  - name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
builds:
  - binary: tfaction
    main: cmd/tfaction/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
release:
  prerelease: true
  header: |
    [Pull Requests](https://github.com/suzuki-shunsuke/tfaction/pulls?q=is%3Apr+milestone%3A{{.Tag}}) | [Issues](https://github.com/suzuki-shunsuke/tfaction/issues?q=is%3Aissue+milestone%3A{{.Tag}}) | https://github.com/suzuki-shunsuke/tfaction/compare/{{.PreviousTag}}...{{.Tag}}
signs:
  - cmd: cosign
    artifacts: checksum
    signature: ${artifact}.sig
    certificate: ${artifact}.pem
    output: true
    env:
      - COSIGN_EXPERIMENTAL=1
    args:
      - sign-blob
      - --output-signature
      - ${signature}
      - --output-certificate
      - ${certificate}
      - --oidc-provider
      - github
      - ${artifact}
