---
name: test
on: workflow_call

jobs:
  test:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version: 1.20.3
          cache: true
      - uses: aquaproj/aqua-installer@294926f94b4233f202a2f03875c604f840cfed70 # v2.1.1
        with:
          aqua_version: v2.3.4
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      - run: golangci-lint run --timeout 120s
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      - run: go test -v ./... -race -covermode=atomic
      - run: go install ./cmd/pinact
      - run: pinact -v
      - run: pinact run testdata/foo.yaml
      - run: git diff
